### ISSUE TITLE
split tsv data error

### ISSUE THREAD

**Issue by QYinyourmind** [google-research-datasets/wit#3]
which character denotes the end of every row? I try '\n' but got many in context_section_description column..How to fix this?

**Comment by krishna2** [comment]
The files are tab separated and the rows are newline separated. However, there are some columns that do have the newline character - especially if they are long text. If you use, for e.g., something like Python's native csv module, then it will parse the data correctly.

Here is an example:
https://docs.python.org/3/library/csv.html#csv.reader

Hope that helps.
