### ISSUE TITLE
Baseline Models in WIT Paper

### ISSUE THREAD

**Issue by iamjanvijay** [google-research-datasets/wit#9]
Do you plan to release the baseline models pre-trained on WIT dataset (as mentioned in WIT paper)? Thank you!

**Comment by krishna2** [comment]
Sorry, no model release as part of this work. But recent / modern models are so much more powerful and easily available.

**Comment by sandeepjana** [comment]
The models trained on WIT can be commercial friendly unlike many other models! So +1 for model release.

**Comment by krishna2** [comment]
Sorry no model release as part of this work and a lot has changed in the last two years (since our dataset release).
